### ISSUE TITLE
enable SpotMarketRequest 

### ISSUE THREAD

**Issue by johnstudarus** [terraform-providers/terraform-provider-packet#109]
Currently, this test is disabled possibly related to API/Platform issues. It needs to be re-enabled.

https://github.com/terraform-providers/terraform-provider-packet/commit/4f58b1d9b11f48a7fe1f72e26e1abe1072cd4ca0

**Comment by t0mk** [comment]
I removed that commit from the PR - the Spot Market Request test is enabled again
