### ISSUE TITLE
Terraform 0.12 Support 

### ISSUE THREAD

**Issue by dopry** [terraform-providers/terraform-provider-packet#118]
It would be nice if the provider support Terraform 0.12. As of 2019/03/07, [Terraform 0.12 is in beta](https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1). 

It brings a number of [features that simplify complex terraform configurations and improve the general developer experience](https://www.hashicorp.com/blog/terraform-0-1-2-preview) with Terraform.

**Comment by t0mk** [comment]
@dopry Thanks for filing the isue. We will track the progress on 0.12 update here.

**Comment by dopry** [comment]
@t0mk  has begun development on 0.12 support.
```
$ git clone --branch 0.12 https://github.com/t0mk/terraform-provider-packet
$ cd terraform-provider-packet
$ make
```
