### ISSUE TITLE
Unable to replace reserved instances

### ISSUE THREAD

**Issue by mikesimos** [terraform-providers/terraform-provider-packet#124]
### Terraform Version
`0.11.13`

### Affected Resource(s)
Please list the resources as a list, for example:
- `packet_device`

### Terraform Configuration Files
```hcl
resource "packet_device" "REDACTED" {
  hostname         = "REDACTED"
  project_id       = "${packet_project.REDACTED.id}"
  operating_system = "ubuntu_16_04"
  facility         = "ewr1"
  plan             = "baremetal_2a2"
  hardware_reservation_id = "next-available"
  billing_cycle    = "hourly"
  user_data        = "${file("./path/to/user_data.yml")}"
}
```

### Panic Output
```
Error: Error applying plan:
1 error(s) occurred:
* packet_device.REDACTED: 1 error(s) occurred:
* packet_device.REDACTED: There are no available hardware reservations for selected plan and facility
```

### Expected Behavior
The device should have been reprovisioned, reusing its hardware reservation.

### Actual Behavior
`terraform apply` failure. Success was **not** possible for several minutes, even with the hardware reservation appearing as unused in the dashboard, and the previous device completely removed.

### Steps to Reproduce
1. `terraform apply`

**Comment by t0mk** [comment]
@mikesimos Thanks for reporting this, I will take a look!

**Comment by mikesimos** [comment]
Thank you @t0mk!  To add some context, after one hour or so, I was able to use the released hardware reservation without issues via tf. It's just that this behavior complicates operations.

**Comment by t0mk** [comment]
@mikesimos can you please drop a link to the dashboard where you see the reservation as released? I usually work with the API, I don't have good overvirew of the app.packet.net.

I have my own project with a reservation for testing.

**Comment by mikesimos** [comment]
The main issue for me was that `terraform apply` just fails to update the state if we are on a reserved hardware instance.

**Comment by t0mk** [comment]
I understand. Can you check what's the reservation status over the API? I mean after you destroy the device, when the `apply` fails. 
`curl --silent -X GET -H "X-Auth-Token: $PACKET_AUTH_TOKEN" "https://api.packet.net/projects/<project_id>/hardware-reservations?exclude=plan" | jq ".hardware_reservations"`

.. spcifically the `provisionable` attribute? For me it takes ~4 minutes after I remove the device in the reservation, until the `provisionable` is true. When it's true, `terraform apply` creates the device (with hw res `next-available`)

I think the 4 minutes is reasonable for the deprovisioning.

**Comment by t0mk** [comment]
If you want to chat, I'm online in https://packetcommunity.slack.com/messages/C9DECH3GA/

**Comment by t0mk** [comment]
I could make the Delete action of device on reserved hardware (conditionally on attribute) hang until the hw-reservation is marked provisionable, that might perhaps do it for you. so you could do sth like

```
resource "packet_device" "REDACTED" {
  hostname         = "REDACTED"
  project_id       = "${packet_project.REDACTED.id}"
  operating_system = "ubuntu_16_04"
  facility         = "ewr1"
  plan             = "baremetal_2a2"
  hardware_reservation_id = "next-available"
  wait_reservation_deprovision = true,
  [...]
}
```

**Comment by mikesimos** [comment]
Heya, sorry I 'm in the middle of a few things..
The api request yields (among others):
```json
"device": null,
"provisionable": false
```
for that specific reservation for some minutes here too.

Adding a `wait_reservation_deprovision` sounds awesome! I 'm guessing it can't be the default behavior, right?

**Comment by t0mk** [comment]
@mikesimos, you can only put new device to the reservation when it's `provisionable: true`. If you think it takes too long time, please create support ticket in the app.

OK, I will do `wait_for_reservation_deprovision`. I think it needs to be false by default, to keep things fast out-of-the-box.

**Comment by mikesimos** [comment]
Cool! Thank you @t0mk !

**Comment by t0mk** [comment]
Hey @mikesimos, we just had a new release of the provider. Please check if this arg:
https://www.terraform.io/docs/providers/packet/r/device.html#wait_for_reservation_deprovision

will fix this issue for you. Thanks!
