### ISSUE TITLE
Terraform shows device as "still creating" even though it is active

### ISSUE THREAD

**Issue by BRMatt** [terraform-providers/terraform-provider-packet#138]
### Terraform Version

`11.3`

### Affected Resource(s)

- packet_device (using version 1.7.1 of the provider)

### Terraform Configuration Files

```hcl
resource "packet_device" "vm-builder" {
  hostname         = "${random_pet.server-name.id}"
  plan             = "c2.medium.x86"
  facility         = "nrt1"
  operating_system = "ubuntu_16_04"
  billing_cycle    = "hourly"
  project_id       = "${var.packet_project_id}"
  description      = "${packet_ssh_key.ephemeral.id}"
}
```

### Expected Behavior

When creating a packet device through terraform, terraform will stop waiting for the device to be created when packet.net's API reports the device as active.

### Actual Behavior

The API reports the device as ready within ~10 minutes, but terraform continues to wait for the device "to be created" 30+ minutes after the device was created.

Here are some normal (not debug) terraform logs showing it waiting on the device, as well as the API response from `/projects/{id}/devices` that I captured using packet.net's API docs approx 30 minutes after the terraform run started.

https://gist.github.com/BRMatt/11b0a86c75693515b1953f2bddf1d8e6

The servers no longer exist, so I don't think the contents are sensitive.

Here is an image of events in the packet.net console showing that the device was "ready to go" ~11 minutes after creation:

<img width="955" alt="Image 2019-04-09 at 6 04 01 pm" src="https://user-images.githubusercontent.com/20394/55819965-e8270400-5af1-11e9-9e1d-0ce3fd05b63c.png">
<img width="940" alt="Image 2019-04-09 at 6 05 27 pm" src="https://user-images.githubusercontent.com/20394/55820043-11e02b00-5af2-11e9-8de2-f7dd19c4f95f.png">

It's also worth noting that if I delete the devices through the web ui while terraform is waiting for them to become ready the packet provider appears to ignore the fact the device no longer exists and signals to terraform that everything's ok?

```
packet_device.vm-builder: Still creating... (40m40s elapsed)
  | packet_device.vm-builder: Still creating... (40m50s elapsed)
  | packet_device.vm-builder: Still creating... (41m0s elapsed)
  | packet_device.vm-builder: Still creating... (41m10s elapsed)
  | packet_device.vm-builder: Still creating... (41m20s elapsed)
  | packet_device.vm-builder: Still creating... (41m30s elapsed)
  | packet_device.vm-builder: Creation complete after 41m37s
  |  
  | Error: Error applying plan:
  |  
  | 1 error(s) occurred:
  |  
  | * null_resource.provision-builder: Resource 'packet_device.vm-builder' does not have attribute 'id' for variable 'packet_device.vm-builder.id'
  |  
  | Terraform does not automatically rollback in the face of errors.
  | Instead, your Terraform state file has been partially updated with
  | any resources that successfully completed. Please address the error
  | above and apply again to incrementally change your infrastructure.

```

**Comment by t0mk** [comment]
Hey @BRMatt , thanks for submitting the issue. I will take a deeper look tomorrow.

Can you reproduce this? It would be really good to see TF debug log. You can collect it as
```
TF_LOG=DEBUG terraform apply &> log
```
.. it records all the HTTP traffic, and it will show what exactly is the API sending, and why it doesn't finish. If you decide to submit the log here, please remember to remove lines with X-Auth-Token header.

Thanks!

**Comment by BRMatt** [comment]
Hi @t0mk I ran that earlier and it showed that Terraform was making the API requests successfully, but the debug logs only include the request/response headers, not the response body. Is that what you want to see?

**Comment by BRMatt** [comment]
And yes, currently this is very reproducible.

**Comment by BRMatt** [comment]
Ok, I realised that `TF_LOG=trace` dumps the response bodies, so I was able to capture this: https://gist.github.com/BRMatt/d7c6a855d4dcc90a580333a5a33f72c1

The device became ready in the packet.net terminal ~5-10 minutes ago, but it's still stuck in this loop.

If it's useful, this machine is a c2.medium.x86, provisioned in nrt1

**Comment by t0mk** [comment]
@BRMatt Thanks for the debug log.

I think the problem is that the packet_device module also waits for `network_type` to be `layer3` (You can see network type in app.packet.net in the sever detail, in the network tab.)
The API reports it to be still `layer2-bonded` but it's in fact `layer3`. I don't know if you can about the network type. Anyway, this issue is caused by this API bug:
https://github.com/packethost/packngo/issues/141

It's really bad that the simple API caching bug is causing this behaivor. I will fix and ask for re-release first thing tomorrow (Eastern european time). Unfortunately, the wait for the layer3 network state is baked in, os there is no elegant workaround.

Maybe try to specify packet provider version to 1.4.1, that's before the network_type support.
To specify provider version:
https://www.terraform.io/docs/configuration/providers.html#version-provider-versions
