### ISSUE TITLE
Add description  to the "packet_reserved_ip_block" resource type

### ISSUE THREAD

**Issue by morenod** [terraform-providers/terraform-provider-packet#163]
Elastic IPs supports description when creating them, but `packet_reserved_ip_block` module doesn't have this parameter created.

**Comment by t0mk** [comment]
hey @morenod, thanks for reporting, I fix this in #166.

It will be out in next release of the provider, probably within a couple of weeks. I could ask for release earlier if you really need to use this. Let me know.
