### ISSUE TITLE
Error Message Missing on State Error

### ISSUE THREAD

**Issue by jmarhee** [terraform-providers/terraform-provider-packet#167]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.12.6                                                                                                       + provider.packet v2.2.1                                                                                                +   
```

### Affected Resource(s)
packet_device

### Terraform Configuration Files
Not specific to any one configuration

### Debug Output
https://gist.github.com/jmarhee/d94c55525fbcfcefb92c9cf601ff662a

### Expected Behavior
The `last error` field should have contained a string containing an error message:

```hcl
Error: unexpected state 'failed', wanted target 'active'. last error: 'some error'
```

### Actual Behavior
This field returned a nil value:

```hcl
Error: unexpected state 'failed', wanted target 'active'. last error: %!s(<nil>)
```

### Steps to Reproduce
Running `terraform apply` while provisioning is disabled on Packet. This has not reoccurred during other types of provisioning failures, for which there were errors.

**Comment by t0mk** [comment]
Hey @jmarhee Thanks for reporting. I will take a look next week.

**Comment by t0mk** [comment]
hi, @jmarhee I know that this is hard to reproduce, but I would appreciate if you could review PR #175 which should fix this.
