### ISSUE TITLE
Allow to specify timeout on packet_device creation

### ISSUE THREAD

**Issue by morenod** [terraform-providers/terraform-provider-packet#170]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
Please list the resources as a list, for example:
- packet_device.

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
15:44:42 packet_device.masters.2: Still creating... (22m0s elapsed)
15:44:52 packet_device.masters.2: Still creating... (22m10s elapsed)
15:45:02 packet_device.masters.2: Still creating... (22m20s elapsed)
15:45:12 packet_device.masters.2: Still creating... (22m30s elapsed)
15:45:22 packet_device.masters.2: Still creating... (22m40s elapsed)
15:45:32 packet_device.masters.2: Still creating... (22m50s elapsed)
15:45:42 packet_device.masters.2: Still creating... (23m0s elapsed)
15:45:52 packet_device.masters.2: Still creating... (23m10s elapsed)
15:46:02 packet_device.masters.2: Still creating... (23m20s elapsed)
15:46:12 packet_device.masters.2: Still creating... (23m30s elapsed)
15:46:22 packet_device.masters.2: Still creating... (23m40s elapsed)
15:46:32 packet_device.masters.2: Still creating... (23m50s elapsed)
15:46:42 packet_device.masters.2: Still creating... (24m0s elapsed)
15:46:52 packet_device.masters.2: Still creating... (24m10s elapsed)
15:47:02 packet_device.masters.2: Still creating... (24m20s elapsed)
15:47:12 packet_device.masters.2: Still creating... (24m30s elapsed)
15:47:22 packet_device.masters.2: Still creating... (24m40s elapsed)
15:47:32 packet_device.masters.2: Still creating... (24m50s elapsed)
15:47:42 packet_device.masters.2: Still creating... (25m0s elapsed)
15:47:52 packet_device.masters.2: Still creating... (25m10s elapsed)
15:48:02 packet_device.masters.2: Still creating... (25m20s elapsed)
15:48:12 packet_device.masters.2: Still creating... (25m30s elapsed)
15:48:22 packet_device.masters.2: Still creating... (25m40s elapsed)
15:48:32 packet_device.masters.2: Still creating... (25m50s elapsed)
15:48:42 packet_device.masters.2: Still creating... (26m0s elapsed)
15:48:52 packet_device.masters.2: Still creating... (26m10s elapsed)
15:49:02 packet_device.masters.2: Still creating... (26m20s elapsed)
15:49:12 packet_device.masters.2: Still creating... (26m30s elapsed)
15:49:22 packet_device.masters.2: Still creating... (26m40s elapsed)
15:49:32 packet_device.masters.2: Still creating... (26m50s elapsed)
15:49:36 
15:49:36 Error: Error applying plan:
15:49:36 
15:49:36 1 error occurred:
15:49:36 	* packet_device.masters[2]: 1 error occurred:
15:49:36 	* packet_device.masters.2: provisioning time limit exceeded; the Packet team will investigate

### Expected Behavior

Allow to increase/decrease default timeout 

### Actual Behavior

When packet fails to create a server, terraform waits 30min without possibility of configuring another value

**Comment by t0mk** [comment]
hi @morenod, can you please review #174, it should fix this
