### ISSUE TITLE
Terraform sometimes fails when using "next-available" and a specific hash for hardware_reservation_id

### ISSUE THREAD

**Issue by rata** [terraform-providers/terraform-provider-packet#176]
### Terraform Version
```
$ terraform -v
Terraform v0.11.13
+ provider.packet v1.7.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- packet_device

### Terraform Configuration Files
```
resource "packet_device" "a" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
   count            = 10
  .... 

  hardware_reservation_id = "next-available"
}

resource "packet_device" "b" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 

  hardware_reservation_id = "some-hash"
}

```

### Expected Behavior
If `"some-hash"` is a valid reservation id and there are 10 more reservations for `t1.small.x86` instances on the same facility, then:

 * 11 servers should be created
 * `packet_device.b` resource should use the reservation id `"some-hash"`
 * 10 other servers should use other the other reservation ids

### Actual Behavior

`packet_device.b` sometimes fails to be created because the reservation id is already taken by some server in `packet_device.a` terraform resource.

The `facility` and `instance_type` values are not important. The only thing that matters is that they are the same. The `count=10` is only to make this race condition more likely to happen, using a bigger number might make it even more likely if you have issues reproducing.

The problem, IIUC, seems to be that terraform by default uses parallelism 10. Therefore, is totally possible (specially when creating 50+ servers) that the 10 servers from `packet_device.a` are created and one of the reservation ids used by them is `"some-hash"`. Later, when `packet_device.b` is created, the reservation is already in use and therefore `packet_device.b` fails to be created.

Basically, there is a race condition there and the same terraform file may work or not depending on how Packet API assigns reservation ids.

AFAICS, there is nothing that can be done on the Packet API as terraform request for servers with specific reservation ids are not even made and Packet is behaving as expected: using any reservation id that matches. The problem is that later terraform does a request for packet_device.b and it reservation might be used. Packet is behaving correctly, but the terraform user might be surprised by this.

I'm not familiar with the code, but I'm not sure there is an easy solution for this :-/

An idea that might be worth investigating (let me know if it doesn't make sense): I think terraform uses different HTTP requests to the Packet API for each server, and maybe something worth looking is at the batch API Packet has? However, I haven't tested if servers are created as expected when using the batch API. Furthermore, I'm not sure if it's possible to use this from a terraform provider, as the `count` variable may be something more generic and, maybe, terraform forces different request for different devices? Really, no idea here :)

The workaround that I'm doing is using `terraform apply -target` to create nodes with specific reservation ids first, and then the others. But, besides this being really ugly, not sure if terraform provides a way to do such a thing for a provider (never wrote one, sorry :)).

In that case, maybe terraform has the assumption that the devices are independant and, when having such functionlity in the terraform module, they are clearly not (one server depends on the reservation other used to be possible to create it)? Maybe some terraform fundamental assumption was broken (in this very subtle way) when exposing this?

Don't get me wrong, I really like this functionality (and using "next-available" is really convenient), but it breaks when mixing it with specific hashes. I need to use specific hashes for several different reasons (for BGP ECMP to work with Packet EIP you need servers to be on different racks, or for running a kubernetes control plane, you may want servers to be on different racks and therefore use specific hardware reservations to ensure that). I can share more on the use cases, if you need more info :)

Can you think of any way to make such a file (or any file mixing "next-available" and specific hashes) work reliably?

### Steps to Reproduce
1. `terraform apply`

**Comment by rata** [comment]
The equivalent of doing `terraform apply -target` workaround is forcing a dependency.

Having a `depends_on` or similar should do the trick, to force the creation of one before the other. And if all devices with specific hashes are forced to be created before the ones with `"next-available"`, using this `depends_on` trick or similar way to achieve a dependency, this should work.

It is still very hacky, of course. And documentation might need to be added and rely on the user on explicitelly creating these dependencies. So... not the best user experience :)

As I was discussing this with @invidian, other improvements might be possible at the packet API (like tagging reservation ids? excluding some reservation ids from the "next-available" thing?)

Cc: @invidian as we discussed this in person and had these ideas and helped me clarify this :)

**Comment by t0mk** [comment]
@rata thanks for reporting. I read your description briefly and I will get back to it maybe later this week.

A quick check - are you aware that you can control tf parallelism? If you do
`terraform apply --parallelism 1` then everything willl be run sequentialy, no concurrent goroutines.

**Comment by rata** [comment]
@t0mk Hi! Thanks for the answer :)

Yes, I'm aware. That will not solve the issue, though. It's not really about parallelism, it's about the order in which packet_devices are created when using hardware reservation id.

To put it short: let's say you want to create two packet device (A and B) and you have two hardware reservations on Packet ("my-id" and "other-id"). In terraform, A is specified with hardware reservation id "my-id" and B with "next-available". If the request to create B is done first, Packet will assign any reservation id available, in some cases it may assign "my-id". Then, when a request to create A is done, if B was assigned "my-id", it will fail as the reservation "my-id" is already in use.

Does it make more sense now? Let me know if I'm not being clear, I know I'm not the best to explain myself sometimes :)

(the only subtle thing is that the "next-available" uses any reservation id that matches the facility and instance type. Therefore, A and B should be in the same facility and be the same instance type. But hopefully this is better explained on my original report :))

**Comment by jasmingacic** [comment]
This is definitely API issue. Terraform is issuing HTTP requests too quickly and the same hardware reservation gets allocated between two devices. I don't see what could be done on the TF side to fix this issue.

Let's keep this open so it can be tracked.

**Comment by rata** [comment]
@jasmingacic It is **not** about HTTP request being too quickly, is just the order HTTP requests are created. And it's really not clear if it's an API issue, IMHO. The API is working as expected: the API serves the request with the params it has properly, for every single HTTP request.

Let me give another example:

```
resource "packet_device" "a" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
   count            = 10
  .... 

  hardware_reservation_id = "next-available"
}

resource "packet_device" "b" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 

  hardware_reservation_id = "some-hash"
}
```

The **only** way to guarantee that this terraform file will met the user expectations with current API is if `packet_device.b` is created first. If not, the reservation `"some-hash"` **can** be used when creating `packet_device.a`.

Please note that if things happen in this order:
 1. packet_device.a is created. Any reservation id is requested, so `"some-hash"` is assigned by the API (totally legit)
1. b creation fails. The api fails that the reservation specified is being used (totally legit and valid)

The API is doing the right thing at every step, yet the user expectation is not met (what I described in the original report as expected behaviour)

The issue is at the terraform layer, IMHO, that creates independent HTTP requests in any order and the request are not independent: if one request is created before another, you may correctly get different results. But just guessing terraform does that, didn't check the code (seems like it for the executions I had).

However, to better support these kind of use cases (creating HTTP request in any order as if they were independent but they really aren't), improvements in the API might be needed or an option to move forward (like create a request with "next-available" but don't use `"some-hash"`).

I'm not familiar with terraform providers (mentioned some options in previous comments, not sure if really possible), so not sure what it can be done. Maybe an assumption is that different terraform devices wouldn't care about between themselves ordering? We are really breaking that here, but not sure if it is an invariant terraform imposes to providers, just guessing.

What options do you think we have?

**Comment by jasmingacic** [comment]
So you just confirmed that if you pass in a specific hash it will work as expected but if you pass `next-available` it will eventually error out. 
If that is the case then the API is not fetching the next available hash internally. Probably when `next-available` fetches the hash but at the same time another request happens which tries (internally)to use the same hash. This is probably because the hash that has been taken from the queue was not marked as taken.
I've seen similar things happen with some other providers.

Please correct me if I'm wrong

**Comment by jasmingacic** [comment]
Actually I re-read your comments. Disregard my previous comments

For example you've got 10 hardware reservations and you do this:
```
resource "packet_device" "a" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
   count            = 10
  .... 

  hardware_reservation_id = "next-available"
}
```
and this with a specific UUID:
```
resource "packet_device" "b" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 

  hardware_reservation_id = "some-hash"
}
```

Effectively you will creating 11 devices using reserved hardware of which you have 10 slots. This scenario is going to fail 100%.

**Comment by rata** [comment]
@jasmingacic that is not **AT ALL** what I'm talking about. Sorry I wasn't clear.

In that example you posted, of course you have 11 reservations. See the original post that says:

> If "some-hash" is a valid reservation id and there are 10 **more** reservations for t1.small.x86 instances on the same facility

So, really, that is not the case.

I think the example here is more clear, maybe. Can you please check it out: https://github.com/terraform-providers/terraform-provider-packet/issues/176#issuecomment-545653208 ?

Let me put it again, just the example, as the bug is really simple and I'm not sure what I'm forgetting to say that is driving conversations like this.

```
 resource "packet_device" "a" {
    plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 

  hardware_reservation_id = "next-available"
 }
 
 resource "packet_device" "b" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 

  hardware_reservation_id = "some-hash"
}
```
Of course, you have 2 hardware reservations: "some-hash" and some other.

> Please note that if things happen in this order:
>
> 1. packet_device.a is created. Any reservation id is requested, so "some-hash" can be assigned by the API (totally legit)
> 2. b creation fails. The api fails that the reservation specified is being used (totally legit and valid)

The API is doing the right thing at every step, yet the user expectation is not met (only one node is created instead of 2).

However, if you do the HTTP requests in another order than (create b, then a), then both servers will be created just fine.

And this is the issue: sometimes it works with terraform and someitmes it doesn't, because HTTP request are done in "any" order.

@jasmingacic is the issue clear now?

**Comment by rata** [comment]
@t0mk  @jasmingacic friendly ping? :)

**Comment by jasmingacic** [comment]
@rata This is something engineering should look into. I will gladly share this with them.

**Comment by rata** [comment]
@jasmingacic thanks!

**Comment by rata** [comment]
@t0mk friendly ping?

**Comment by t0mk** [comment]
@rata Right now I don't have the means to test this (enough hw reservations) but I will ask for it, and also I will ask if I can dedicate time to this.
I assume that if you have 10 hw reservations you are not-that-small of a customer?
Can I get your email, so I can CC you in email conversation?

**Comment by rata** [comment]
@t0mk it can be reproduced with 1 hw reservation, though. Is just less likely :)

In any case, is the root cause understood now? I don't think it is so important to reproduce it to understand the root cause of the problem.

You can cc me with my work address: rodrigo@kinvolk.io. We have good a relationship with Packet, they surely remember me :-)

**Comment by t0mk** [comment]
@rata I think you need at least 2 hw reservations to test the unconditional success of 
```
resource "packet_device" "a" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 
  hardware_reservation_id = "next-available"
}

resource "packet_device" "b" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 
  hardware_reservation_id = "some-hash"
}
```
I think I understand the root cause, but I am not sure how to fix it. AFAIK it's **not possible** to
- affect the order of created resources from within the provider code.
- specify which hw-res hash to exclude when using next-available.

Considering both of those points, I don't know how to solve this in the provider code (by my means).

However, you can specify the order of resources explicitly. Would it actually help if you had the `next-available` packet_device resource [explicitly depend_on](https://learn.hashicorp.com/terraform/getting-started/dependencies.html#implicit-and-explicit-dependencies) the resource with hw-res hash?

e.g.
 
```
resource "packet_device" "a" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 
  hardware_reservation_id = "next-available"
  depends_on = [packet_device.b]
}

resource "packet_device" "b" {
   plan             = "t1.small.x86"
   facilities       = ["ams1"]
  .... 
  hardware_reservation_id = "some-hash"
}
```

Then the `some-hash` reservation is used before the "next-availables".

**Comment by rata** [comment]
@t0mk oops, right, 2 hw reservations. Sorry :)


Yeah, I don't know either. I'm not sure it is possible 

> I think I understand the root cause, but I am not sure how to fix it. AFAIK it's **not possible** to
> 
> * affect the order of created resources from within the provider code.

Yeah, I'm not sure if some other tricks can be used.

For example, as I mentioned before, the Packet API has a batch option. If the packet batch api can be used and if all requests are submitted at the same time the Packet API might be able to handle that correctly.

I don't think terraform provides that flexibility to the provider (to do one big request for all resources), as it has a `parallelism` flag at a more generic level. So, my guess here is that the provider can't do that in a reasonable way. But this is a very uninformed guess.

Also, there might be other problems even if this that I have not tested it (submitting all the requests to the packet batch api), works. For example, one potential problem might be that there might be a max number of request to batch, so maybe the problem is still possible just when requests that split in different batches. Not sure.

But too much speculation here, those things should be tested and investigated :-)

> * specify which hw-res hash to exclude when using next-available.

Yeah, that might need changes to packet API as suggested. And not sure is the right path in the long term. What do you think?

> Considering both of those points, I don't know how to solve this in the provider code (by my means).

Yeah, me neither :-/

> However, you can specify the order of resources explicitly. Would it actually help if you had the `next-available` packet_device resource [explicitly depend_on](https://learn.hashicorp.com/terraform/getting-started/dependencies.html#implicit-and-explicit-dependencies) the resource with hw-res hash?

Yes, something like that is the hack that I'm doing (actually, I'm using `terraform apply -target` but it achieves the same, as I mentioned in a previous comment :)).

I'm not sure, however (terraform always surprises me) if having a dependency there can be a problem during the life-cycle of the servers. Like, if the resource `b` crashes or is modified (like the instance_type is modified), not sure what will happen to resource `a`. I'd like to play a little bit with that before going down this route. Can you see any obvious problem in the resources life-cycle when adding such a dependency?

Those are doubts that need to be verified if they are a problem or not and that is it. But I do have some concerns even if that (adding a `depends_on`) works, though: I think documentation should be pretty clear as this is definitely something not intuitive. And user experience might not be very good. My concerns with that are mostly the ones mentioned here: https://github.com/terraform-providers/terraform-provider-packet/issues/176#issuecomment-538349519.

But, at least in the short-term, it seems like the most reasonable way is to document this limitation and advise the user to use `depends_on` (if we don't find any side effect of the `depends_on`). Do you think it makes sense?

I can write such a patch if you this seems fine for you, let me know if you have any opinions on where it should be (as it is not a trivial explanation, maybe a big note on the resource instead of the `hardware_reservation` param description?).

One other thing that worries me is that it feels very wrong. I've not written a provider, but it seems like we are breaking a terraform invariant (something like "resources are independent" or something like that) just because exposing that (very very useful, though) things of the Packet API.

What do you think?


Thanks a lot and sorry for the long replies and confusing bug report :)

**Comment by t0mk** [comment]
Hey @rata, thanks for your comment.

> For example, as I mentioned before, the Packet API has a batch option. If the packet batch api can be used and if all requests are submitted at the same time the Packet API might be able to handle that correctly.

You are right that there are [batches](https://www.packet.com/developers/api/#create-a-devices-batch) in the Packet API, and that the batch resource is missing in the provider. I've never done it for obvious reason - the `count` meta-parameter for TF resource cuts most of the use-cases for batches (and there is one less resource and less code to maintain and grow bugs).

Now when I read through the batch doc,  I see that there are some features in the batch API resource, which might be worth having in Terraform, e.g the facility diversifying. However, I don't think you can specify the hw reservation in the batch. And even if you could use `next-available`, you would still need to ensure that it won't take the hw reservation hash that you specify later for another device, i.e. you would still need to use `apply -target` or `depends_on`. 

Using the batch API in the packet_device resource is out of question. The HashiCorp people would burn me at stake for something like that :).

>> * specify which hw-res hash to exclude when using next-available.

> Yeah, that might need changes to packet API as suggested. And not sure is the right path in the long term. What do you think?

This could be theoretically done with another optional attr in the device creating HTTP POST, maybe `"hardware_reservation_exclude" [<uuid1>, <uuid2>, ...]`. The attr would be valid only with `next-available`. I find this clumsy, and even if it would exist, I'd rather use the `depends_on` (just to avoid using a uuid or a variable twice). If you think it's useful, you should suggest it to your contact in Packet engineering. I could do that myself, but I think you are more motivated about it, and it's more likely to be noticed if it comes from a customer.

> I'm not sure, however (terraform always surprises me) if having a dependency there can be a problem during the life-cycle of the servers. Like, if the resource b crashes or is modified (like the instance_type is modified), not sure what will happen to resource a. I'd like to play a little bit with that before going down this route. Can you see any obvious problem in the resources life-cycle when adding such a dependency?

I think `depends_on` is only "creational dependency". TF should not re-create explicitly dependent resource when linked dependency is tainted and forced to re-create. If you worry about destroying some resource, there are measures to safeguard, you should check the [lifecycle meta-param](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations).

> But, at least in the short-term, it seems like the most reasonable way is to document this limitation and advise the user to use depends_on (if we don't find any side effect of the depends_on). Do you think it makes sense?

I totally agree, the doc is [here](https://github.com/terraform-providers/terraform-provider-packet/blob/master/website/docs/r/device.html.markdown), the `hardware_reservation_id` and `next_available` is documented in Argument Reference. Please submit PR explaining it. Or I can do it if you don't have time, let me know.

> One other thing that worries me is that it feels very wrong. I've not written a provider, but it seems like we are breaking a terraform invariant (something like "resources are independent" or something like that) just because exposing that (very very useful, though) things of the Packet API.

The semantics of the `hardware_reservation_id` is obviously not so great already. The `depends_on` is in Terraform for use-cases like this. I wouldn't worry about it.

I hope I answered most of your questions. Possible actions to resolve this would then be

* check if batches can do `next-available` for hw res. If yes, think if having batch resource in the provider resolves this use-case.
* lobby for `"hardware_reservation_exclude" [<uuid1>, <uuid2>, ...]` in combination with `next-available` in packet_device
* PR for `hardware_reservation_id` in packet_device, explaining that `depends_on` should be used when mixing `next-available` and UUIDs.

**Comment by rata** [comment]
> Hey @rata, thanks for your comment.

Thank you! :-)

> > For example, as I mentioned before, the Packet API has a batch option. If the packet batch api can be used and if all requests are submitted at the same time the Packet API might be able to handle that correctly.
> 
> You are right that there are [batches](https://www.packet.com/developers/api/#create-a-devices-batch) in the Packet API, and that the batch resource is missing in the provider. I've never done it for obvious reason - the `count` meta-parameter for TF resource cuts most of the use-cases for batches (and there is one less resource and less code to maintain and grow bugs).

Yes, of course :-)

> Now when I read through the batch doc, I see that there are some features in the batch API resource, which might be worth having in Terraform, e.g the facility diversifying. However, I don't think 
you can specify the hw reservation in the batch. And even if you could use `next-available`, you would still need to ensure that it won't take the hw reservation hash that you specify later for another device, i.e. you would still need to use `apply -target` or `depends_on`.

Good point, it would not even completely solve the problem :-/

> 
> Using the batch API in the packet_device resource is out of question. The HashiCorp people would burn me at stake for something like that :).

Agreed :-)

> 
> > > * specify which hw-res hash to exclude when using next-available.
> 
> > Yeah, that might need changes to packet API as suggested. And not sure is the right path in the long term. What do you think?
> 
> This could be theoretically done with another optional attr in the device creating HTTP POST, maybe `"hardware_reservation_exclude" [<uuid1>, <uuid2>, ...]`. The attr would be valid only with `next-available`. I find this clumsy, and even if it would exist, I'd rather use the `depends_on` (just to avoid using a uuid or a variable twice). If you think it's useful, you should suggest it to your contact in Packet engineering. I could do that myself, but I think you are more motivated about it, and it's more likely to be noticed if it comes from a customer.

I'm not sure it's worth it, it can be complicated when lists start to get too big (like let's say you have tons of reservations) and it doesn't seem worth adding that complexity. What do you think?

> > I'm not sure, however (terraform always surprises me) if having a dependency there can be a problem during the life-cycle of the servers. Like, if the resource b crashes or is modified (like the instance_type is modified), not sure what will happen to resource a. I'd like to play a little bit with that before going down this route. Can you see any obvious problem in the resources life-cycle when adding such a dependency?
> 
> I think `depends_on` is only "creational dependency". TF should not re-create explicitly dependent resource when linked dependency is tainted and forced to re-create. If you worry about destroying some resource, there are measures to safeguard, you should check the [lifecycle meta-param](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations).
> 

I'd play with it, and read more docs, to verify. Just don't remember these things from the top of my head :-)

> > But, at least in the short-term, it seems like the most reasonable way is to document this limitation and advise the user to use depends_on (if we don't find any side effect of the depends_on). Do you think it makes sense?
> 
> I totally agree, the doc is [here](https://github.com/terraform-providers/terraform-provider-packet/blob/master/website/docs/r/device.html.markdown), the `hardware_reservation_id` and `next_available` is documented in Argument Reference. Please submit PR explaining it. Or I can do it if you don't have time, let me know.

I'd give it a try in the next weeks, if you think is not critical to have this PR ASAP (it is something that was there forever, so I don't think is causing real pain to users... I don't think is very urgent to do it ASAP).

> 
> > One other thing that worries me is that it feels very wrong. I've not written a provider, but it seems like we are breaking a terraform invariant (something like "resources are independent" or something like that) just because exposing that (very very useful, though) things of the Packet API.
> 
> The semantics of the `hardware_reservation_id` is obviously not so great already. The `depends_on` is in Terraform for use-cases like this. I wouldn't worry about it.

Yeah, seems about right. If you are creating a module with `packet_device` resources, though, it can be trickier (as module don't accept `depends_on` and you will have to do another output/input to do emulate this). But... yeah, at least as short-term, it seems the best we can do. Thanks! :-)

> 
> I hope I answered most of your questions. Possible actions to resolve this would then be
> 
> * check if batches can do `next-available` for hw res. If yes, think if having batch resource in the provider resolves this use-case.
> * lobby for `"hardware_reservation_exclude" [<uuid1>, <uuid2>, ...]` in combination with `next-available` in packet_device
> * PR for `hardware_reservation_id` in packet_device, explaining that `depends_on` should be used when mixing `next-available` and UUIDs.

I'll start with item 3 in the next weeks, if that is okay.

I'm not sure about item 2 (maybe something can be improved in another way?) and it should be nice to check item 1, but as far as we discussed it wouldn't solve the problem, right? So, not very high prio, IMHO.


Thanks again for all your time!

**Comment by rata** [comment]
@t0mk Do you think we should close this?

**Comment by t0mk** [comment]
Yes, as nothing else besides the docs can be done, and the docs are in
place:
https://www.terraform.io/docs/providers/packet/r/device.html#hardware_reservation_id

I think we can close this.

**Comment by rata** [comment]
Thanks!
