### ISSUE TITLE
vlan resource tests fail

### ISSUE THREAD

**Issue by t0mk** [terraform-providers/terraform-provider-packet#182]
Failing acceptance tests

Following tests notoriously fails in Hashicorp Teamcity:

They are all the L2 ports assigning tests.

TestAccPacketPortVlanAttachment_Hybrid 
TestAccPacketPortVlanAttachment_HybridMultipleVlans
TestAccPacketPortVlanAttachment_L2Bonded
TestAccPacketPortVlanAttachment_L2Individual
TestAccPacketPortVlanAttachment_L2Native

The error is always

```
the facility dfw2 has no provisionable s1.large.x86 servers matching your criteria
        
          on /opt/teamcity-agent/temp/buildTmp/tf-test955797134/main.tf line 6:
          (source code not available)
     
```

The facility must be changed or found out during runtime based on capacity.

**Comment by jasmingacic** [comment]
I've tried running tests but for whichever reason devices get stuck in "queued" state and then it errors out.
