### ISSUE TITLE
terraform cannot deprovision hosts while volumes are attached.

### ISSUE THREAD

**Issue by coryschwartz** [terraform-providers/terraform-provider-packet#199]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
11 (I think 12 is also affected, though)

### Affected Resource(s)
Please list the resources as a list, for example:
- packet_device
- packet_volume_attachment
- packet_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output

1 error occurred:
	* module.gateway_stage1.packet_volume_attachment.vol_gateway_attachment (destroy): 1 error occurred:
	* packet_volume_attachment.vol_gateway_attachment: DELETE https://api.packet.net/storage/attachments/d667a610-4c67-48b4-8dcd-409337e7dc55: 422 Cannot detach since volume is actively being used on your server 

### Expected Behavior
There should be some option for one of the following:
* destroy "attachments" prior to deleting the device 
* destroy devices using the "force_delete" option in the api
https://www.packet.com/developers/api/#delete-the-device

### Actual Behavior
While the attachment is active (that is, while the iscsi initiator is attached to the target), packet does not permit the "attachment" endpoint to be deleted. In order to delete the volume attachment, you must first log out of the iscsi initiator.

Packet provides a script to log out in and out of iscsi, which comes pre-installed on a few devices.
https://github.com/packethost/packet-block-storage

On creation tasks, the volume attachment depends on the volume and the device to come up first. Once iscsi is logged in, however, terraform cannot destroy the configuration in the reverse order -- attachment first, then volume and device. 

I know this is tricky since it's it's difficult to know whether data can be unmounted. However, when there are device failures or when the server becomes unreachable, it would be nice if there were an option to deprovision the server and leave the volume intact without.

**Comment by t0mk** [comment]
Hi @coryschwartz, thanks for your report.

You are right that you can't destroy devices with attached volumes via Terrraform at the moment. However, if you use TF resources for attaching the volume, the Packet provider should destroy them in proper order.

I have just tried to create and destroy this:

```
resource "packet_device" "test_device_va" {
  hostname         = "terraform-test-device-va"
  plan             = "baremetal_0"
  facilities       = ["ewr1"]
  operating_system = "ubuntu_16_04"
  billing_cycle    = "hourly"
  project_id       = "${local.project_id}"
}

resource "packet_volume" "test_volume_va" {
  plan = "storage_1"
  billing_cycle = "hourly"
  size = 100
  project_id = "${local.project_id}"
  facility = "ewr1"
}

resource "packet_volume_attachment" "test_volume_attachment" {
  device_id = "${packet_device.test_device_va.id}"
  volume_id = "${packet_volume.test_volume_va.id}"
}
```
.. and both apply and destroy works OK.

But if you attach the volume out of Terraform, it will not destroy the device unless you detach it manually.

This Terraform provider doesn't run the Packet storage scripts, it doesn't fit in the Terraform concept. However, it coould be run from the remote-exec provisioner somehow.

I didn't know about force_delete. I will consider adding it to the packet_device resource. Thanks for suggesting this.

**Comment by t0mk** [comment]
hi @coryschwartz, thanks for reporting, i am looking at this. do you have a tf template which would use the remote-exec provisioner (https://www.terraform.io/docs/provisioners/remote-exec.html) to attach the volume over SSH?
It would be helpful for testing. I can do it myself if you run the attach script manually.
