### ISSUE TITLE
bgp resource fails to provision IPV6

### ISSUE THREAD

**Issue by coryschwartz** [terraform-providers/terraform-provider-packet#206]
### Affected Resource(s)
Please list the resources as a list, for example:
- packet_bgp_session

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "packet_bgp_session" "gateway_bgp_ipv4" {
  device_id = "${packet_device.gateway.id}"
  address_family = "ipv4"
}

resource "packet_bgp_session" "gateway_bgp_ipv6" {
  device_id = "${packet_device.gateway.id}"
  address_family = "ipv6"
}
```

### Debug Output

The first run
```
Error: Error applying plan:
2 errors occurred:
	* module.gateway_stage1.packet_bgp_session.gateway_bgp_ipv4: 1 error occurred:
	* packet_bgp_session.gateway_bgp_ipv4: Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble.
	* module.gateway_stage2.packet_bgp_session.gateway_bgp_ipv4: 1 error occurred:
	* packet_bgp_session.gateway_bgp_ipv4: Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble.
```

and then subsequent runs:
```
Error: Error applying plan:
2 errors occurred:
	* module.gateway_stage2.packet_bgp_session.gateway_bgp_ipv4: 1 error occurred:
	* packet_bgp_session.gateway_bgp_ipv4: Address family already has session with ipv4
	* module.gateway_stage1.packet_bgp_session.gateway_bgp_ipv4: 1 error occurred:
	* packet_bgp_session.gateway_bgp_ipv4: Address family already has session with ipv4
```

### Expected Behavior
I should be able to have BGP sessions for IPV6 and IPV4

### Actual Behavior
IPV4 sessions are created, IPV6 sessions need to be enabled using the packet web UI.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
I think I might know what's going on here. While the address_family is read from the configuration, it is ignored and only "ipv4" is used when creating the session.

https://github.com/terraform-providers/terraform-provider-packet/blob/master/packet/resource_packet_bgp_session.go#L55

**Comment by t0mk** [comment]
@coryschwartz thanks for the report. I'm sad that this went through, it's my fault, sorry.

Thanks for #207 PR, I will run acceptance tests, and then merge tomorrow. New release maybe Friday 6.12.

**Comment by coryschwartz** [comment]
@t0mk Thank you! :)

**Comment by t0mk** [comment]
Hey @coryschwartz provider containing fix for this has just been released. Please update your provider and test :)
