### ISSUE TITLE
terraform apply hangs if device creation takes too long time

### ISSUE THREAD

**Issue by t0mk** [terraform-providers/terraform-provider-packet#211]
When creating e.g. ESXi devices (which take <15 min) to provision, the provider hangs.

The culprit is: the provider waits for the devices to get to the active state. A device with VMWare ESXi takes sometimes <15 minutes to intialize (until Packet API lists its state as "active"). The provider checks the state of the device by querying the API every 10 secs. The component responsible for the checking has max timeout set for 1 hour, i.e. it should check the API resource for the new device every 10 seconds for one hour.

However, for some reason, the provider stops querying the API after 12-15 minutes. After that time, it stops issuing the HTTP GETs, and it passively waits, not getting any refreshs. The devices becomes "active" in the Packet API, but the TF provider is not aware because the API HTTP requests ceased. It still hangs, and probably would die in one hour.

After some digging, I noticed that the call to client.Do of the retryablehttp client just doesn't return at some point (after the 12 minutes). It seems the goroutine doing the HTTP query just dies. I am not sure why exactly. I need to spend more time debugging.

**Comment by enkelprifti98** [comment]
This issue was fixed for me as of Packet provider 2.7.1. @c0dyhi11 Are you still experiencing device creation hangs?
