### ISSUE TITLE
ipxe_script_url should not conflict with non-ipxe user_data 

### ISSUE THREAD

**Issue by bzub** [terraform-providers/terraform-provider-packet#22]
### Affected Resource(s)
- packet_device

### Expected Behavior
The provider allows ipxe_script_url="something" && user_data="anything" as long as user_data doesn't start with `#!ipxe`

### Actual Behavior
```
* packet_device.controller: "ipxe_script_url": conflicts with user_data ("${data.ct_config.controller.*.rendered[count.index]}")                                                                                     
* packet_device.worker: "ipxe_script_url": conflicts with user_data ("${data.ct_config.worker.*.rendered[count.index]}")
```

### References
This bug was introduced (by me) in #16. The code creates a conflict between `ipxe_script_url` and `user_data` fields, when actually this should only cause an error if `user_data` is an ipxe script.

**Comment by t0mk** [comment]
Is this really a bug? I mean, can a device run from iPXE still get user-data blob from Packet metadata service? Isn't there some plumbing in the Packet OS images that makes the user-data fetch happen?

To ask differently: The way to download user-data is somehow standard? And Packet exposes user-data in this standard way?

Sorry if the question is silly, I'm a user-data noob.

**Comment by bzub** [comment]
I might be the only person that uses `custom_ipxe` in this way 😆. I know that with CoreOS, at least, one is able to make the packet metadata scripts available the same way as if packet.net were provisioning the device, and thus use the user_data and anything else like normal. In my case I added an initrd like to the script ipxe_script_url points to that adds the packet-specific OEM files.

**Comment by bzub** [comment]
Here's the script if you're curious: https://raw.githubusercontent.com/cloudnativelabs/pxe/master/packet/coreos-stable-packet.ipxe

**Comment by t0mk** [comment]
Thanks for explanation. Looks legit to me.
