### ISSUE TITLE
packet_reserved_ip_block is broken

### ISSUE THREAD

**Issue by t0mk** [terraform-providers/terraform-provider-packet#227]
I noticed that project attribute disappeared from the Reserved IP block API resource:
https://github.com/packethost/packngo/issues/174

Because that attribute disappeared from the resource, TF can't find out the project_id of a reserved_block resource (it will evaluate to "."), and every `terraform plan` will mark a packet_reserved_ip_block for re-creation.

This is most likely because of a change in the API, which took away the `project` attribute if the resources at /ips/<block_uuid>.

Looking at the CI tests of the provider, the API change that caused this happened around 25th of March 2020.

Until this is fixed, the packet_reserved_ip_block resource is broken, because TF will not be able to detect the project_id and will try to recreate.

**Comment by vielmetti** [comment]
This has been fixed in the API; @t0mk if you can validate the fix, we can close this out.

**Comment by mmlb** [comment]
I've verified that after our api rollout I am no longer seeing an issue.

**Comment by t0mk** [comment]
@vielmetti @mmlb great, thanks. I checked the provider acceptance tests of the reserved block resource, they got back to green.
