### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by andfasano** [terraform-providers/terraform-provider-packet#228]
Sometimes, but not regularly, our Terraform script fails with the error message containing:

`read: connection reset by peer`

Despite the error, looks like the Packet server still gets created. How can we handle correctly such error?

Thanks

**Comment by t0mk** [comment]
Hey @andfasano, thanks for the report. Can you please specify what happens in more detail?

Does the error make the terraform run fail? We have some resilience inbuilt in the provider, and in case of TCP errors (like $SUBJ), it should retry.

Are you able to invoke the error? If yes, can you please capture the HTTP traffic for me like this:

`TF_LOG=DEBUG TF_LOG_PATH=tflog  terraform apply -auto-approve`

.. thanks!

**Comment by andfasano** [comment]
Hi t0mk,
we were not able to replicate it until now.
