### ISSUE TITLE
JSON schema changed?

### ISSUE THREAD

**Issue by andfasano** [terraform-providers/terraform-provider-packet#230]
Hi,
today we had a failure in the code related to extract the public ip from the `terraform.tfstate` file (see below), could you please confirm if something is changed?

`jq -r '.modules[0].resources["packet_device.server"].primary.attributes.access_public_ipv4' terraform.tfstate` 

Thanks
Andrea

**Comment by t0mk** [comment]
Hi @andfasano, I don't recall anything changing in the access_public_ipv4. Can you see anything in the state file under the access_public_ipv4?

**Comment by vielmetti** [comment]
Hi @t0mk @andfasano - there was a note in a parallel discussion about a map being transformed into an array.

**Comment by stbenjam** [comment]
Look like it's not the providers fault, we upgraded from terraform 0.11 to 0.12  and the schema changed of tfstate.

https://github.com/openshift/installer/blame/aa8452beb656b11239bd63e477c61bb2adb798d4/images/installer/Dockerfile.upi.ci#L41

**Comment by vielmetti** [comment]
Thanks @stbenjam - it looks like the stable way to extract data from tfstate should be through `terraform output` https://www.terraform.io/docs/commands/output.html in case the tfstate schema changes again.

**Comment by andfasano** [comment]
Thanks for the quick feedback, I'll close the issue then
