### ISSUE TITLE
Provide a useful error message if auth_token is invalid

### ISSUE THREAD

**Issue by bzub** [terraform-providers/terraform-provider-packet#24]
I noticed that if `auth_token` is set, but invalid, we do not seem to output a useful error message.

The only case I've tested so far is creating a `packet_ssh_key` resource and `api_token` set to `""` empty string. I'll test to see if this is for all packet resources, and show an example in an update to this issue.

In provider.go we do not do any validation against `auth_token` currently. I assume the packet API returns an unauthorized response, which we should also let the user know of if anything gets past validation.

**Comment by t0mk** [comment]
I confirm this, I run simple acceptance test with wrong PACKET_AUTH_TOKEN, and output is not very helpful:

```
--- FAIL: TestAccPacketReservedIPBlock_Basic (0.60s)
	testing.go:449: Step 0 error: Error applying: 1 error(s) occurred:
		
		* packet_project.foobar: 1 error(s) occurred:
		
		* packet_project.foobar: 
FAIL
exit status 1

```
