### ISSUE TITLE
always_ipxe not supported

### ISSUE THREAD

**Issue by voobscout** [terraform-providers/terraform-provider-packet#3]
Packet [API](https://www.packet.net/developers/api/devices/) has a nifty ```"always_pxe": "boolean"```

```json
{
	"facility": "string",
	"plan": "string",
	"hostname": "string",
	"description": "string",
	"billing_cycle": "string",
	"operating_system": "string",
	"always_pxe": "boolean",
	"ipxe_script_url": "string",
	"userdata": "string",
	"locked": "boolean",
	"spot_instance": "string",
	"tags": [
		"string"
	],
	"project_ssh_keys": [
		"string"
	],
	"user_ssh_keys": [
		"string"
	],
	"features": [
		"string"
	]
}
```
Any chance this will be implemented in terraform? Right now i'm forced to make an additional local-exec provisioner, that updates the API to enable the always_ipxe, it seems rather convoluted for something so simple...

**Comment by bzub** [comment]
I'd like to have this feature also. One issue with implementation is that the official Go library doesn't support always_pxe yet either.

I've implemented it, though, in the library and this provider. Soon I'll probably get time to make sure it's good enough to submit a pull request.

Here are my forks:
https://github.com/bzub/packngo
https://github.com/bzub/terraform-provider-packet

For now you can the provider by running `go get github.com/bzub/terraform-provider-packet`
Then add/merge this into ~/.terraformrc
```
providers {                                                                                                                                                                                                          
  packet = "${GOPATH}/bin/terraform-provider-packet"                                                                                                                                                                                                                                                                                                                         
}
```

**Comment by voobscout** [comment]
@bzub Thanks! You're awesome!

**Comment by mmlb** [comment]
packngo has been updated and now has always_pxe support
