### ISSUE TITLE
Explore support for Packet's local and global BGP feature

### ISSUE THREAD

**Issue by bzub** [terraform-providers/terraform-provider-packet#31]
It's on the Packet.net public roadmap as a feature request. I'd like to use it also.
https://trello.com/c/TNuos7rW

**Comment by jasmingacic** [comment]
@bzub The BGP feature is supported with in the API but there seems to be a problem with delete. There is a pending PR https://github.com/packethost/packngo/pull/90

**Comment by t0mk** [comment]
closed by #88
