### ISSUE TITLE
failover if certain server is not available in particular facility at the moment

### ISSUE THREAD

**Issue by kphatak** [terraform-providers/terraform-provider-packet#32]
### Terraform Version
0.10.7

### Affected Resource(s)
- packet_device

### Terraform Configuration Files
```hcl
 provider "packet" {
   auth_token = ""
 }

 variable "project_id" {
   type = "string"
 }

 resource "packet_device" "first-deploy" {
   hostname         = "tf.test"
   plan             = "baremetal_0"
   facility         = "sjc1"
   operating_system = "centos_7"
   billing_cycle    = "hourly"
   project_id       = "${var.project_id}"
 }
```

### Debug Output
https://gist.github.com/kphatak/88cb22fdaea8f1b607868e75dfc46548

### Expected Behavior
Ideally, provider should accept multiple facilities and host types and retry on failure with a certain type of error

### Actual Behavior
Provider errors out with servers unavailable error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. check what server type is unavailable from UI for a particular facility
2. Provision using terraform for that facility and server type

**Comment by jasmingacic** [comment]
@kphatak This doesn't seems to be a Terraform issue but rather with the platform itself.

**Comment by patrickdevivo** [comment]
@kphatak there's now a feature in the Packet API that let's users supply a list of facilities to indicate placement preference: https://www.packet.net/developers/api/#create-a-device

That is about to be added to the golang sdk, which should make it's way into this provider

**Comment by jacobsmith928** [comment]
@patrickdevivo can you link to the packngo issue or PR for context?

**Comment by patrickdevivo** [comment]
@jacobsmith928 it's already in the latest `master` branch, and will be in the next release (when we're able to cut one). Here's the relevant PR: https://github.com/packethost/packngo/pull/112

**Comment by t0mk** [comment]
@kphatak now this is possible with
https://www.terraform.io/docs/providers/packet/r/device.html#facilities
