### ISSUE TITLE
Custom partitioning and RAID support

### ISSUE THREAD

**Issue by t0mk** [terraform-providers/terraform-provider-packet#34]
In Packet it's possible to define custom partitioning and RAID config in a device creation parameter:
https://help.packet.net/technical/storage/custom-partitioning-raid

It would be nice to have this in TF provider.

The `storage` parameter format is (at first glance) the same as in CoreOS Ignition, supporting disks, filesystems and raid types:

```
{
 "disks":<array of subobjects>,
 "filesystems":<array of subobjects>,
 "raid":<array of subobjects>, <- optional
}
```

As this is nicely structured, it could be done in a more sophisticated way than just JSON string.

There's already a TF provider for Ignition, so I will look on how the schema are defined there:
https://github.com/terraform-providers/terraform-provider-ignition

Thanks to @bzub for pointing me to Ignition (IMO it wouldn't hurt to mention it in the Packet CPR doc).

**Comment by t0mk** [comment]
I think I will keep it TypeString. If I would like to capture types, couldn't avoid maps of maps, and that doesn't play well with TF, as we've seen with the IP addresses.

The `storage` param then will be a JSON map. I will have to make sure that order of keys in the maps does not matter - that changing key order will not trigger resource update. I plan to do it by Unmarshaling to map[string]interface{} and then Marshaling to string. The Go [json.Marshal](https://golang.org/pkg/encoding/json/#Marshal) is ordering the keys somehow. I hope I will be able to pre-process the param value somehow.

**Comment by bzub** [comment]
I should clarify what I said in slack and repost for here. Packet seems to use CoreOS Ignition to do this disk configuration step, and as you mentioned it works for most (any?) OS they offer. They most likely run ignition as a preliminary step with this config fed to it, then apply OS specific installation steps on top of that new disk configuration. So we shouldn't be concerned with the OS here.

I will have to verify if this config is 100% ignition config JSON, if so then we could possibly leverage existing provider code and/or ignition libraries.

**Comment by t0mk** [comment]
I did look on ignition provider, and considered to reuse the schemas. But to structure the storage param would mean nested maps and lists. As the storage is optional param, I think it's more straightforward to do it as a json string.
