### ISSUE TITLE
spot_instance not supported

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-packet#38]
`spot_instance` is in the API , similar to #3

**Comment by bzub** [comment]
This feature is implemented in https://github.com/terraform-providers/terraform-provider-packet/pull/27 however the Packet API doesn't meet the expectations of Terraform maintainers, so unfortunately we are waiting for a more robust spot_instance implementation in the Packet API.

**Comment by matti** [comment]
https://github.com/terraform-providers/terraform-provider-packet/issues/59

**Comment by jasmingacic** [comment]
#72 This has been implemented with this PR.

**Comment by t0mk** [comment]
@matti this is done and released. Go ahead and give it a try.
