### ISSUE TITLE
user_data and ipxe_script_url should be usable simultaneously

### ISSUE THREAD

**Issue by ZoidBB** [terraform-providers/terraform-provider-packet#39]
### Terraform Version
Terraform v0.11.1
+ provider.packet v1.1.0
+ provider.tls v1.0.1

### Affected Resource(s)
 - packet_device

### Expected Behavior
defining both ipxe_script_url and user_data fields should apply fine

### Actual Behavior
terraform incorrectly informs me that ipxe_script_url and user_data fields conflict

**Comment by t0mk** [comment]
fixed by #23
