### ISSUE TITLE
Add `description` to the "packet_device" resource type

### ISSUE THREAD

**Issue by jonasfj** [terraform-providers/terraform-provider-packet#41]
Packet instances supports a `description` property, see [API docs](https://www.packet.net/developers/api/devices/).

It would be nice if we could set this property from terraform.

### Terraform Configuration Files
```hcl
resource "packet_device" "pxe1" {
  description      = "my machine created for cool project..."  // not currently supported
  hostname         = "tf.coreos2-pxe"
  plan             = "baremetal_1"
  facility         = "ewr1"
  operating_system = "custom_ipxe"
  billing_cycle    = "hourly"
  project_id       = "${packet_project.cool_project.id}"
  ipxe_script_url  = "https://rawgit.com/cloudnativelabs/pxe/master/packet/coreos-stable-packet.ipxe"
  always_pxe       = "false"
  user_data        = "${data.ignition_config.example.rendered}"
}
```

---
From a quick look at the source this seems easy to do... if I get some idle time I might give it a shot.

**Comment by t0mk** [comment]
Hi @jonasfj, I just asked for a release without a fix to this. I don't have time to fix this now, and it seems really cosmetic. Furthermore, it seems it's not possible to set or update this field in the Packet portal.

**Comment by jonasfj** [comment]
Agree, this is a tiny cosmetic thing....

Mostly useful for completeness :)

**Comment by jasmingacic** [comment]
This seems to be fixed. Can someone close the issue?
