### ISSUE TITLE
resourcePacketDeviceUpdate doesn't update user_data, lets set ForceNew

### ISSUE THREAD

**Issue by jonasfj** [terraform-providers/terraform-provider-packet#42]
I modified the `user_data` of a machine deployed, then ran `terraform apply` only to find that it pretended to something, when in fact it didn't do anything?

Expected behavior:
 * Delete and recreate the instance
 * Update user-data and reboot the instance
 * Update user-data (and nothing more)
 * Fail to update user-data and report this as not implemented

Neither of these things was attempted, it seems unwise to implement `resourcePacketDeviceUpdate` when you implement it to silently pretend to do a thing it doesn't do. It does **not** update the resource, it does however report it as updated.

I'll admit I'm a bit new at terraform, but if we just remove the implementation won't terraform fallback to deleting and recreating the resource, which honestly seems like a better plan. In the case of immutable infrastructure this is perfectly fine (not ideal, but fine), in the case of someone who has pets, the `terraform plan` should warn that this will delete the resource.  Terraform even comes with built-in `lifecycle` options to ignore changes on mutable infrastructure.

**Comment by jonasfj** [comment]
After reading terraform docs another time, I suggest just adding `ForceNew` for the `user_data` property.

This is probably desired in many cases, since `user_data` is normally used to configure the instance. Most systems won't detect new `user_data` and take action accordingly, rather they'll have to be rebooted or even formatted, in case packages was installed, etc.

**Comment by jonasfj** [comment]
@t0mk

I guess we can close this issue...

A quick look at the update function suggests to me that anything other than "locked" should be either computed or `ForceNew`.

As we currently only support updating the locked property..

maybe we should do a quick check to see if there is other properties that need to be ForceNew. It's a pretty easy fix after all :)

**Comment by t0mk** [comment]
Thanks @jonasfj, I just went through the params. Yes, the solely computed attrs can be ignored for the ForceNew.

`ipxe_script_url` and `always_pxe` was I think introduced by @bzub, I wonder if there is any reason why those 2 should not be ForceNew. I.e. to me it seems reasonable that change in ipxe_script_url should taint the device resource state and force Terraform to recreate it.

Then, there are `tags`, and those should be updateable (just like they are in the Packet app), so I guess there's a piece of code missing in the `resourcePacketDeviceUpdate` func in the device resource.

**Comment by jonasfj** [comment]
Yeah, I'm pretty sure `ipxe_script_url` and `always_pxe` should be `ForceNew`. It doesn't really make sense to pxe boot a machine from existing state :) I doubt that even supported.

For `tags` I would argue that until we've fixed `resourcePacketDeviceUpdate` it's better to have `ForceNew`. As terraforming is primarily about synchronizing state, whether it's done by update or delete/recreate is less important. Afaik the update function is even optional, I suspect/hope that if not implemented everything will just be `ForceNew` :)
