### ISSUE TITLE
resource packet_project doesn't support import

### ISSUE THREAD

**Issue by zakhark** [terraform-providers/terraform-provider-packet#45]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.3
+ provider.packet v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- packet_project

### Terraform Configuration Files
```
provider "packet" {
  auth_token = "${var.auth_token}"
}

resource "packet_project" "t1" {
  name           = "T1"
}
```

### Debug Output
```
$ terraform import packet_project.t1 xxxxxx
packet_project.t1: Importing from ID "xxxxxx"...

Error: packet_project.t1 (import id: xxxxxx): import packet_project.t1 (id: xxxxxx): resource packet_project doesn't support import

```
### Panic Output
n/a

### Expected Behavior
Being able to import an existing project

### Actual Behavior
packet_project doesn't support import

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform import packet_project.t1 %project_id%`

### Important Factoids
I have an existing project that I want to import into terraform because it has reserved instances attached to it.

### References
n/a

**Comment by zakhark** [comment]
Thanks for the prompt reply, @t0mk 

TF import does fail to import project by ID.
But looking at https://www.terraform.io/docs/import/importability.html I see that none of packet resources are listed so probably it's an expected behavior. It would be nice if imports were supported though.

**Comment by t0mk** [comment]
@zakhark, OK, let's keep this open unti the import is possible. I will not be able to touch this until at least the end of this week.

Did you solve your use case? If I'd like to refer to project ID in my TF templates, I'd rather define a variable, than import an existing project (https://www.terraform.io/docs/configuration/variables.html), but of course there might be scenarios where project import makes more sense.

**Comment by t0mk** [comment]
project import is possible now

**Comment by vielmetti** [comment]
@t0mk - there is a report from @benschza linked here regarding project import, can you lend advice?
