### ISSUE TITLE
Updating `ipxe_script_url` "works" but doesn't actually work

### ISSUE THREAD

**Issue by grahamc** [terraform-providers/terraform-provider-packet#46]
> Terraform v0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
 - packet_device

### Terraform Configuration Files
```hcl
variable "auth_token" {}
variable "project_id" {}
variable "ipxe_script_url" {}

provider "packet" {
  auth_token = "${var.auth_token}"
}

# Create a device and add it to tf_project_1
resource "packet_device" "web1" {
  hostname         = "my-server"
  plan             = "baremetal_2a"
  facility         = "ewr1"
  operating_system = "custom_ipxe"
  ipxe_script_url  = "${var.ipxe_script_url}"
  always_pxe       = true
  billing_cycle    = "hourly"
  project_id       = "${var.project_id}"
}
```

### Debug Output
I left this out because it was too hard to strip out the secrets.

### Panic Output
na

### Expected Behavior

Running terraform apply should update the PXE URL configured for the host.

### Actual Behavior
What actually happened?

```
$ terraform apply
packet_device.web1: Refreshing state... (ID: ...)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ packet_device.web1
      ipxe_script_url: "02-10v1/netboot.ipxe" => "bogus/netboot.ipxe"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

packet_device.web1: Modifying... (ID: ...)
  ipxe_script_url: "02-10v1/netboot.ipxe" => "bogus/netboot.ipxe"
packet_device.web1: Modifications complete after 1s (ID: ...)
```

but the device's pxe URL is not updated. Running terraform apply again tries to do it again, as well.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. change the URL in the config
3. terraform apply again, notice the URL isn't updated on the server

**Comment by t0mk** [comment]
hi @grahamc thanks for the report.

Before I fix this, I would like to ask for your input:
In #41 we discussed whether there's a sense in updating the PXE URL on a device - if you want to boot from a different pxe image, maybe you actually need a fresh device.

In other words - Can you come up with a scenario where you _really_ want to update PXE URL without re-creating the device?

**Comment by grahamc** [comment]
Note that while I do strongly believe that this is a viable and useful workflow, I wouldn't be offended if Terraform didn't support it. I understand Terraform's model creates natural restrictions in how flexible a provider can be, and you need to make decisions on how this provider works.

The root of the issue for me is that Terraform says it can update the PXE URL, tries to, says it _did_ update the URL, but in the end it didn't. As long as the provider does something reasonable and tells me the truth about what it is going to do, I'm satisfied. Even if I would prefer a technically-and-sensibly-updatable-field to be actually-updatable.

**Comment by grahamc** [comment]
P.S. I find this provider useful, and I'm glad it exists. Thank you for your work on it, it makes a big difference to me.

**Comment by grahamc** [comment]
Thank you a lot!
