### ISSUE TITLE
Provider crashes when trying to rename ssh key

### ISSUE THREAD

**Issue by BRMatt** [terraform-providers/terraform-provider-packet#47]
### Terraform Version

```console
$ terraform -v
Terraform v0.11.3
+ provider.null v1.0.0
+ provider.packet v1.2.0
```

### Affected Resource(s)
- `packet_ssh_key`

### Terraform Configuration Files

```hcl
provider "packet" {
  auth_token = ""
}

resource "packet_ssh_key" "foobar" {
  name = "packer-foobar-hello"
  public_key = "${file("./ssh_keys/id_rsa.pub")}"
}
```

You can generate the ssh key using

```console
$ ssh-keygen -t rsa -C "used for sshing into ephemeral packet.net instances" -P '' -f ssh_keys/id_rsa
```

### Debug Output

Panic output is at the end of the gist

https://gist.github.com/BRMatt/23051b8816a2f75175f1f86fb48bea95

### Expected Behavior

The Packet provider should've renamed the ssh key, and updated the state file.

### Actual Behavior

The provider renamed the ssh key, but crashed before the state file could be be update.

### Steps to Reproduce

1. `terraform apply`
1. change the `name` attribute of the `packet_ssh_key`
1. `terraform apply` crashes

**Comment by t0mk** [comment]
@BRMatt Thanks for the report. I am looking at this and I see what the culprit is. I will try to fix it by today.

**Comment by t0mk** [comment]
OK, this goes deeper - to https://github.com/packethost/packngo

**Comment by jasmingacic** [comment]
This seems to be fixed. Can we close this issue?

**Comment by edevenport** [comment]
@BRMatt Can you verify this issue has been corrected now and close the ticket if it has? Thank you.
