### ISSUE TITLE
Elastic IP support

### ISSUE THREAD

**Issue by pgporada** [terraform-providers/terraform-provider-packet#5]
Per https://help.packet.net/technical/networking/elastic-ips, elastic ips are supported by the Packet.net API. This would be nifty to have support for.

**Comment by t0mk** [comment]
We've added 
https://www.terraform.io/docs/providers/packet/r/ip_attachment.html
and
https://www.terraform.io/docs/providers/packet/r/reserved_ip_block.html
to 1.0.0 release.

@pgporada can we close this now? Also, feel free to test the new resources :).

**Comment by pgporada** [comment]
Sure thing :)
