### ISSUE TITLE
Spot-Market-Bid support

### ISSUE THREAD

**Issue by t0mk** [terraform-providers/terraform-provider-packet#59]
In Packet API, there's now support for permanent Spot Market Bid:
https://www.packet.net/resources/changelog/persistent-spot-market-bid/

Previous attempt to support Spot Market Device (a different resource) was rejected because it didn't fit the TF state: #27.

Hopefully, the Spot-Market-Bid is more of a permanent resource, and closer to the (TF-supported) EC2 Spot Instance Request; making it easier to capture by the TF state.

**Comment by radeksimko** [comment]
Based on the article and relevant API docs at https://www.packet.net/developers/api/spotmarketrequest/ it looks like it is what we need to implement it properly. I was unable to verify that these spot requests do not disappear when instances are terminated. I will assume that's just given and "obvious" though.

So I think we're in a good state to implement this as `packet_spot_market_request` resource.

**Comment by jasmingacic** [comment]
I've added the resource #72

**Comment by t0mk** [comment]
this is done and released
