### ISSUE TITLE
Provider Packet doesn't update volume sizes

### ISSUE THREAD

**Issue by johnstudarus** [terraform-providers/terraform-provider-packet#60]
When a Packet volume size attribute is modified, Terraform indicates it will update the volume (with a ~) but no change happens.

Terraform will perform the following actions:

  ~ packet_volume.ETN_2
      size:      "15" => "25"

It appears the resourcePacketVolumeUpdate doesn't actually update the size. The Packet API does support volumes size updates. This function needs to be updated to include code for the size attribute.

https://github.com/terraform-providers/terraform-provider-packet/blob/fc2b8ee6de6dfb40ea6da1147c8f6ced4ef34744/packet/resource_packet_volume.go#L247-L265

The correct action would be for the size to be updated.

Sample output when changing the size from 100 to 222. It says it will change the item but the Packet GUI and the Terraform output still shows the old size.

packet_volume.volume1: Modifying... (ID: 6dd21377-9c3a-4d65-822e-cb0d92e3a959)
  size: "100" => "222"
packet_volume.volume1: Modifications complete after 1s (ID: 6dd21377-9c3a-4d65-822e-cb0d92e3a959)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

Size = 100

studarus@shell:~/Volume$ ./terraform version
Terraform v0.11.7
+ provider.packet v1.2.2

**Comment by t0mk** [comment]
Hey @johnstudarus thanks for reporting.

Yeah, volume update is broken, there's only legacy functionality. I will try to fix this today/tomorrow.

**Comment by t0mk** [comment]
this will be fixed in next release.

@johnstudarus are you comfortable installing provider from this repo? It would be nice to verify.

I wrote tests, but it's always better to review manually.
