### ISSUE TITLE
Create projects under organizations?

### ISSUE THREAD

**Issue by vielmetti** [terraform-providers/terraform-provider-packet#62]
There is support now in the `packngo` API at https://github.com/packethost/packngo/pull/61 for creating projects under specific organizations.

It's not clear to me looking at the docs or at the release notes if this support has made its way into Terraform yet. The report is that all newly created projects in Terraform are created in the default organizations. This is using v1.2.2.

**Comment by miry** [comment]
@t0mk pls check my pr: https://github.com/packethost/packngo/pull/71

**Comment by t0mk** [comment]
fixed by #63
