### ISSUE TITLE
Ability to restore a snapshot on a volume [ENG-368]

### ISSUE THREAD

**Issue by vielmetti** [terraform-providers/terraform-provider-packet#64]
Packet's web interface includes the ability to restore a snapshot on a storage volume. The overview of the volume service is at https://www.packet.net/bare-metal/services/storage/ .

There's a "volumes" interface in the Packet Go API, `packngo`, at https://github.com/packethost/packngo/blob/master/volumes.go

The developer API has (blank) pages at

* https://www.packet.net/developers/api/volumeattachments/
* https://www.packet.net/developers/api/volumesnapshotpolicies/
* https://www.packet.net/developers/api/volumesnapshots/

The desired behavior in Terraform is the ability to restore a snapshot on a volume. From what I can tell, this is going to require some work in `packngo` before this can be done for `terraform-provider-packet`.

**Comment by vielmetti** [comment]
Thanks @t0mk - I'll get answers to these questions before we can proceed.

**Comment by mrmrcoleman** [comment]
Hey @vielmetti were you able to get any clarity on these questions?

**Comment by vielmetti** [comment]
I did not get any clarity on these questions @mrmrcoleman and the need for this has passed. Closing.
