### ISSUE TITLE
[Question] Passing an ssh key when creating a device

### ISSUE THREAD

**Issue by jasmingacic** [terraform-providers/terraform-provider-packet#75]
How can I pass an ssh key when creating a device?

**Comment by johnstudarus** [comment]
You'll want to use the SSH Key Resources. Please see the docs here:

https://www.terraform.io/docs/providers/packet/r/ssh_key.html

For a concrete example, please see:

https://github.com/packet-labs/Packet-Terraform-Project-Boilerplate/blob/master/packet_ssh_key.tf

**Comment by t0mk** [comment]
Now it's possible with 
https://www.terraform.io/docs/providers/packet/r/project_ssh_key.html
