### ISSUE TITLE
Unable to provision reserved instances

### ISSUE THREAD

**Issue by brownjohnf** [terraform-providers/terraform-provider-packet#8]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.10.0

### Affected Resource(s)

- packet_device

Only appears to impact provisioning reserved hardware.

### Terraform Configuration Files
```hcl
# BEGIN Outputs

output "ips" {
  value = "${zipmap(packet_device.arm-builders.*.hostname, packet_device.arm-builders.*.network)}"
}

# END Outputs

# packet_devices.tf

resource "packet_device" "arm-builders" {
  count            = "${var.host_count["arm_builders"]}"
  hostname         = "arm0${count.index + 1}"
  project_id       = "${packet_project.sponsored-testing.id}"
  operating_system = "ubuntu_16_04"
  facility         = "ams1"
  plan             = "baremetal_2a2"
  billing_cycle    = "monthly"
  user_data        = "${file("./user_data/ubuntu/docker-tls.yml")}"
}

resource "packet_project" "sponsored-testing" {
  name = "foobar"
}

# providers.tf

provider "packet" {
  # Specify a PACKET_AUTH_TOKEN env var
}

variable "host_count" {
  type = "map"
  default = {
    arm_builders = "1"
  }
}
```

### Debug Output

https://gist.github.com/brownjohnf/a9a81deba1e431fe3787dff198306bdf

### Panic Output

None

### Expected Behavior

The `baremetal_2a2` should have provisioned.

### Actual Behavior

```
Error applying plan:                                                                                                                                                                                               
1 error(s) occurred:                                                                                                                                                                                               
* packet_device.arm-builders: 1 error(s) occurred:
* packet_device.arm-builders: You are not allowed to provision baremetal_2a2 servers
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using an experimental machine type, but it works fine in the Packet.net dashboard. Also, if I change the type to `baremetal_2a` everything provisions just fine. This seems to be an issue specifically with provisioning reserved instances.

### References

None known of.

**Comment by brownjohnf** [comment]
@vielmetti here's the issue

**Comment by apparentlymart** [comment]
Hi @brownjohnf!

It looks like the packet account we use for dev/testing doesn't list `baremetal_2a2` as a valid plan yet, so I wasn't able to confirm the details of this plan. Can you see this plan listed in [the `plans` API response](https://www.packet.net/developers/api/plans/) if you run it with the API token you're using with Terraform?

If so, could you share the JSON source describing that particular plan so we can get a better sense of what additional constraints might apply here, to understand what Terraform is doing differently than the dashboard here. In particular, I wonder if the experimental nature of this plan means that it's only available in a limited number of facilities, or with other constraints.

**Comment by brownjohnf** [comment]
Sure, I can do that. Ed made some sort of change that unblocked us and got things working, but I then received:

`* packet_device.arm-builders: Billing cycle must be one of the following: hourly`

Switching to an hourly billing cycle allowed me to provision.

**Comment by brownjohnf** [comment]
I do see it in the plans response:

```json
{
			"id": "556d25ec-000f-4a75-86ad-682cc54049fa",
			"slug": "baremetal_2a2",
			"name": "Type 2A2",
			"description": "Our Type 2A2 configuration is a 32-core dual socket ARM server.",
			"line": "baremetal",
			"specs": {
				"cpus": [
					{
						"count": 2,
						"type": "32-core HiSilicon Hi1616 @ 2.4Ghz"
					}
				],
				"memory": {
					"total": "128GB"
				},
				"drives": [
					{
						"count": 1,
						"size": "480GB",
						"type": "SSD"
					}
				],
				"nics": [
					{
						"count": 2,
						"type": "10Gbps"
					}
				],
				"features": {}
			},
			"available_in": [
				{
					"href": "/facilities/8e6470b3-b75e-47d1-bb93-45b225750975"
				}
			],
			"pricing": {
				"hour": 0
			}
		},
```

**Comment by vielmetti** [comment]
Hi all, I made a change to the entitlements that Resin gets (for Packet folks, this is described at ENG-781) that now adds that (as of yet unreleased) device into the plan configuration. What I'm still a little puzzled by is the "pricing" label, as this should only be available in a monthly configuration. I'll investigate further, but I'm glad this is working for now.

**Comment by vielmetti** [comment]
OK, an update.

There is an API call that allows you to provision a reserved instance, documented at https://help.packet.net/technical/infrastructure/reserved-hardware .

It calls the API with a `hardware_reservation_id` parameter, which I don't see in the Terraform code here. That suggests that this is not yet supported.

**Comment by t0mk** [comment]
@brownjohnf : is this still an issue?

We've added https://www.terraform.io/docs/providers/packet/r/device.html#hardware_reservation_id to the device resource.

If it's solved, please feel free to close this.

**Comment by brownjohnf** [comment]
I'll check it out and update this ticket. Thanks.
