### ISSUE TITLE
Device recreated if the facility is "any"

### ISSUE THREAD

**Issue by eloycoto** [terraform-providers/terraform-provider-packet#90]
Hi there,

With the lastest terraform  and provider. 

If I use facility "any" the device is created correctly, but when I tried to scale that facility it will not work as expected, the node that I already have it will change due the facility change. 

Here you havea a `terraform plan` example:  

```
-/+ packet_device.jenkins-node (new resource required)
      id:                      "48826020-162c-4f88-8132-4f192a01a14a" => <computed> (forces new resource)
      access_private_ipv4:     "10.88.99.7" => <computed>
      access_public_ipv4:      "147.75.91.77" => <computed>
      access_public_ipv6:      "2604:1380:1001:2500::7" => <computed>
      always_pxe:              "false" => "false"
      billing_cycle:           "hourly" => "hourly"
      created:                 "2019-01-28T17:40:26Z" => <computed>
      facility:                "sjc1" => "any" (forces new resource)
      hardware_reservation_id: "" => <computed>
      hostname:                "jenkins-node-0" => "jenkins-node-0"
      locked:                  "false" => <computed>
      network.#:               "3" => <computed>
      operating_system:        "ubuntu_18_04" => "ubuntu_18_04"
      plan:                    "baremetal_1" => "baremetal_1"
      project_id:              "ea13e749-0b1b-4c0d-9701-d0a3df7391f2" => "ea13e749-0b1b-4c0d-9701-d0a3df7391f2"
      public_ipv4_subnet_size: "31" => <computed>
      root_password:           <sensitive> => <computed> (attribute changed)
      state:                   "active" => <computed>
      updated:                 "2019-01-28T17:41:50Z" => <computed>
```

The idea is to have something that if the facility is `any` the device does not need to be recreated.

**Comment by t0mk** [comment]
hi @eloycoto thanks for your report. You are right that faclity "any" is not handled properly in the provider. It's because `facility` is not a Computed field and has ForceNew flag set. When it changes from the API, Terraform will try to recreate the device resource. I need to blacklist "any" in the facility.

As for the functionality that "any" provides, this will be added in #83.

**Comment by t0mk** [comment]
@eloycoto for the moment (release 1.2.6), I whitelisted only facility strings. `any` just doesn't work with the provider yet. I understand there's a need for the random-available facility selection, and I am looking for a way to get it through in Terraform. 

It's not a technical problem as such, but the HashiCorp engs just don't like behavior of the `any` attribute. And indeed, it's unprecedented - there's nothing like this in any of the other TF providers.

**Comment by eloycoto** [comment]
@t0mk what about facility can be an array instead of a single string? Packet.net support array for facility: 
https://www.packet.com/developers/api/#create-a-device

**Comment by t0mk** [comment]
@eloycoto I know. I had it done with a comma-separated-list in a string, but it was pushed back by Hashicorp eng:
https://github.com/terraform-providers/terraform-provider-packet/pull/76#pullrequestreview-179394967

A new `facilities` array would be a bti clumsy in the way that, at the moment, it's not possible to properly detect change in list attribute, so if you'd have
```hcl
resource "packet_device" "somedevice" {
  facillites = ["ewr1", "hkg1"]
}
```
.. then run `terraform apply`, the device would be created in ewr1; and then you'd change your `facilities` to

and you'd change it to
```hcl
resource "packet_device" "somedevice" {
  facillites = ["ewr1"]
}
```
.. terraform would re-create the device and there's nothing that I can do about that in the provider.

But maybe that's OK as a limitation. Do you have any thought on that?

**Comment by eloycoto** [comment]
@t0mk main issue that we have: 

Packet.net does not have enough server in EWR, so we need to switch to other location, when we do that the servers need to be recreated, and the older ones can take hours to finish, so Terraform is locking our autosacaling for a lot of time. 

For me, if the facility is an array, and if the device is already created in one of defined facilities the device shouldn't not be deleted. I was thinking/checking other providers examples but I do not found any similar case.

**Comment by t0mk** [comment]
@eloycoto I see. Sorry to hear the provider is locking you down :(.

I will take a look on it on Monday, and will try to
* make `facility` Deprecated and Optional 
* add a new `facilities` attribute - TypeList, ForceNew and Optional attribute, conflicting with `facility`

Let's see how it will roll.

**Comment by t0mk** [comment]
,, `facilities` would allow `any` as well

**Comment by eloycoto** [comment]
@t0mk works for me :-)
