### ISSUE TITLE
Add global IPv4 IP address functionality to packet_reserved_ip_block resource

### ISSUE THREAD

**Issue by jeffbrl** [terraform-providers/terraform-provider-packet#91]
The packet_reserved_ip_block resource currently creates a public IPv4 address. I'd like to see the resource enhanced such that the user can create a public IPv4 or global IPv4 address.

**Comment by t0mk** [comment]
@jeffbrl thanks for your submission. I don't understand what do you miss in the resource. Can you please illustrate?

**Comment by jeffbrl** [comment]
Tony from Packet explained to me on the slack channel that packet_reserved_ip_block does not include a flag to create a global IPv4 address. It currently only creates a public IPv4 address.

**Comment by t0mk** [comment]
@jeffbrl I will take a look on the Public vs Global addresses on Monday.

**Comment by t0mk** [comment]
fixed by #128 and released yesterday. @jeffbrl check from
https://www.terraform.io/docs/providers/packet/r/reserved_ip_block.html
.. the `type` argument.

Please close this issue if you think it's resolved.

**Comment by jeffbrl** [comment]
Possible operator error on my part. "terraform init" isn't downloading 1.4.0

provider.packet: version = "~> 1.3"

**Comment by jeffbrl** [comment]
'terraform init -upgrade' did the trick. Testing now.

**Comment by jeffbrl** [comment]
@t0mk I am able to allocate global_ipv4 addresses in supported sites. Thanks for this enhancement.
